### ISSUE TITLE
The repository contains characters that can not be used by the environment.

### ISSUE THREAD

**Issue by logue** [ravenshining/M1R#10]
The repository file/folder name can not be processed correctly because it contains environment-dependent characters. (such as `?` and `...`)

ex:
```
M1R-splitmap/32 What's Best in Life?/
M1R-splitmap/22 Pfhor Your Eyes Only/Pfhor Your Eyes Only….sceA
```

Could you remove the dependent characters from the file name or directory name and specify in `Level Select Names.txt`?

**Comment by ravenshining** [comment]
Sorry I didn't notice your issue earlier!  It's the first time anyone other than me has opened one :-)  I should make sure GitHub is set to e-mail me for future issues.

Yes, I'll do that, although I am surprised to hear you can't process an ellipsis (…).

Mind you, the map folder's current state relies on symlinks, which may require some effort to get to work right if you are cloning onto a Windows machine.  In the distant future, these symlinks will likely be replaced with actual files.

**Comment by logue** [comment]
Well, it ’s ongoing.
The 35 Try Again folder contains spaces.
```
M1R-splitmap/35 Try again /ai.lua
M1R-splitmap/35 Try again /flash.lua
M1R-splitmap/35 Try again /player.mml
```

**Comment by ravenshining** [comment]
Thanks for spotting that!  Try Again has been fixed with commit 05d44b8.  Are all spaces a problem for your environment or just ending spaces?

**Comment by logue** [comment]
It works correctly! 😃

**Comment by logue** [comment]
Umm...

It terminated at level34...
```
M1R-splitmap/33 savethecolony/invalied level index.sceA
M1R-splitmap/34 Watch 
Aborting
```
Is it the level 34 name contain strange text?

**Comment by ravenshining** [comment]
It shouldn't.  It's just `34 Watch for Ice on Bridge`, and the contents are identical to the previous level because it hasn't been made yet. I'll have to look into this when I get home.
